import { Tourney } from "next/font/google";
import "./globals.css";

const tourney = Tourney({ subsets: ["latin"] });

export const metadata = {
  title: "FridgeBot",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={tourney.className}>{children}</body>
    </html>
  );
}
